# Generated by Django 5.2.8 on 2025-12-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', error_messages={'unique': 'A user with that username already exists.'}, max_length=160, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
